{
    "Value": {
        "ID": "a1923f7a-c4f8-431f-90e9-b767c9174aa1",
        "CategoryID": "32cbf50a-8ff1-e711-80d8-f48e38c2d0c8",
        "Category": {
            "ID": "32cbf50a-8ff1-e711-80d8-f48e38c2d0c8",
            "Code": "",
            "Name": "Education",
            "Image": "http://www.meridians2.com/JacksGoGo/Content/Images/System/1c52341q.png",
            "IsAbleJob": true,
            "IsAbleService": true,
            "IsAbleGoClub": true
        },
        "UserID": "d48533ee-94cf-48bc-b84e-ce441dc5fc61",
        "UserRate": null,
        "Rate": null,
        "RateNumber": null,
        "IsJob": true,
        "Title": "FIND guru",
        "Description": "Boxing professional",
        "Tags": [],
        "Amount": 100000000,
        "CurrencyCode": null,
        "IsUrgent": true,
        "IsSold": null,
        "CreatedOn": "2019-01-09T08:53:00.353",
        "LastActiveOn": null,
        "Status": 0,
        "Location": null,
        "Attachments": [
            {
                "ID": "92810bd2-ccbd-49f4-accd-ab85adf0899d",
                "ReferenceID": "a1923f7a-c4f8-431f-90e9-b767c9174aa1",
                "URL": "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Fsnack-SyI2_wik4-cedea0d1-f88f-470f-bfa7-2051cbfab9d7/ImagePicker/f2767503-faa9-4e73-91a1-1f0ff716c3a9.jpg",
                "Reference": "CreateJob",
                "ReferenceType": 0
            }
        ],
        "User": {
            "Id": "d48533ee-94cf-48bc-b84e-ce441dc5fc61",
            "Surname": null,
            "GivenName": null,
            "Gender": true,
            "Birthday": null,
            "Address": {
                "ADDRESS": "18 HAVELOCK ROAD KINDERLAND PRESCHOOL SINGAPORE 059764",
                "BLK_NO": "18",
                "BUILDING": "KINDERLAND PRESCHOOL",
                "LATITUDE": "1.28763824964793",
                "LONGITUDE": "103.843976681457",
                "LONGTITUDE": "103.843976681457",
                "POSTAL": "059764",
                "ROAD_NAME": "HAVELOCK ROAD",
                "SEARCHVAL": "KINDERLAND PRESCHOOL",
                "X": "29186.156914833",
                "Y": "30006.0174055528",
                "GeoLocation": null
            },
            "PhotoURL": "http://www.meridians2.com/jacksgogo/Content/Images/Profile/4rzg3o0u.jpg",
            "Title": null,
            "Email": "Kong@gmail.com",
            "StripeToken": null,
            "EmailConfirmed": false,
            "PasswordHash": "AAdyLMlLBkYZThjCULVQunsM0GivyK8snkQe2iqZ5EqWfbwWNoRQa/5cSCFfea0dRA==",
            "SecurityStamp": "484f4843-339d-49ad-a1fa-c8160fbb22c7",
            "PhoneNumber": null,
            "PhoneNumberConfirmed": false,
            "TwoFactorEnabled": false,
            "LockoutEndDateUtc": null,
            "LockoutEnabled": false,
            "AccessFailedCount": 0,
            "Overview": null,
            "Rate": 0,
            "Score": null,
            "Points": null,
            "DiscountID": null,
            "Discount": null,
            "CreatedOn": "2018-12-30T15:23:36.753",
            "LastLoggedOn": null,
            "UserName": "Kong",
            "Tags": []
        },
        "Offer": [],
        "Favorite": [
            {
                "User": {
                    "Id": "d48533ee-94cf-48bc-b84e-ce441dc5fc61",
                    "Surname": null,
                    "GivenName": null,
                    "Gender": true,
                    "Birthday": null,
                    "Address": {
                        "ADDRESS": "18 HAVELOCK ROAD KINDERLAND PRESCHOOL SINGAPORE 059764",
                        "BLK_NO": "18",
                        "BUILDING": "KINDERLAND PRESCHOOL",
                        "LATITUDE": "1.28763824964793",
                        "LONGITUDE": "103.843976681457",
                        "LONGTITUDE": "103.843976681457",
                        "POSTAL": "059764",
                        "ROAD_NAME": "HAVELOCK ROAD",
                        "SEARCHVAL": "KINDERLAND PRESCHOOL",
                        "X": "29186.156914833",
                        "Y": "30006.0174055528",
                        "GeoLocation": null
                    },
                    "PhotoURL": "http://www.meridians2.com/jacksgogo/Content/Images/Profile/4rzg3o0u.jpg",
                    "Title": null,
                    "Email": "Kong@gmail.com",
                    "StripeToken": null,
                    "EmailConfirmed": false,
                    "PasswordHash": "AAdyLMlLBkYZThjCULVQunsM0GivyK8snkQe2iqZ5EqWfbwWNoRQa/5cSCFfea0dRA==",
                    "SecurityStamp": "484f4843-339d-49ad-a1fa-c8160fbb22c7",
                    "PhoneNumber": null,
                    "PhoneNumberConfirmed": false,
                    "TwoFactorEnabled": false,
                    "LockoutEndDateUtc": null,
                    "LockoutEnabled": false,
                    "AccessFailedCount": 0,
                    "Overview": null,
                    "Rate": 0,
                    "Score": null,
                    "Points": null,
                    "DiscountID": null,
                    "Discount": null,
                    "CreatedOn": "2018-12-30T15:23:36.753",
                    "LastLoggedOn": null,
                    "UserName": "Kong",
                    "Tags": []
                }
            },
            {
                "User": {
                    "Id": "d48533ee-94cf-48bc-b84e-ce441dc5fc61",
                    "Surname": null,
                    "GivenName": null,
                    "Gender": true,
                    "Birthday": null,
                    "Address": {
                        "ADDRESS": "18 HAVELOCK ROAD KINDERLAND PRESCHOOL SINGAPORE 059764",
                        "BLK_NO": "18",
                        "BUILDING": "KINDERLAND PRESCHOOL",
                        "LATITUDE": "1.28763824964793",
                        "LONGITUDE": "103.843976681457",
                        "LONGTITUDE": "103.843976681457",
                        "POSTAL": "059764",
                        "ROAD_NAME": "HAVELOCK ROAD",
                        "SEARCHVAL": "KINDERLAND PRESCHOOL",
                        "X": "29186.156914833",
                        "Y": "30006.0174055528",
                        "GeoLocation": null
                    },
                    "PhotoURL": "http://www.meridians2.com/jacksgogo/Content/Images/Profile/4rzg3o0u.jpg",
                    "Title": null,
                    "Email": "Kong@gmail.com",
                    "StripeToken": null,
                    "EmailConfirmed": false,
                    "PasswordHash": "AAdyLMlLBkYZThjCULVQunsM0GivyK8snkQe2iqZ5EqWfbwWNoRQa/5cSCFfea0dRA==",
                    "SecurityStamp": "484f4843-339d-49ad-a1fa-c8160fbb22c7",
                    "PhoneNumber": null,
                    "PhoneNumberConfirmed": false,
                    "TwoFactorEnabled": false,
                    "LockoutEndDateUtc": null,
                    "LockoutEnabled": false,
                    "AccessFailedCount": 0,
                    "Overview": null,
                    "Rate": 0,
                    "Score": null,
                    "Points": null,
                    "DiscountID": null,
                    "Discount": null,
                    "CreatedOn": "2018-12-30T15:23:36.753",
                    "LastLoggedOn": null,
                    "UserName": "Kong",
                    "Tags": []
                }
            },
            {
                "User": {
                    "Id": "d48533ee-94cf-48bc-b84e-ce441dc5fc61",
                    "Surname": null,
                    "GivenName": null,
                    "Gender": true,
                    "Birthday": null,
                    "Address": {
                        "ADDRESS": "18 HAVELOCK ROAD KINDERLAND PRESCHOOL SINGAPORE 059764",
                        "BLK_NO": "18",
                        "BUILDING": "KINDERLAND PRESCHOOL",
                        "LATITUDE": "1.28763824964793",
                        "LONGITUDE": "103.843976681457",
                        "LONGTITUDE": "103.843976681457",
                        "POSTAL": "059764",
                        "ROAD_NAME": "HAVELOCK ROAD",
                        "SEARCHVAL": "KINDERLAND PRESCHOOL",
                        "X": "29186.156914833",
                        "Y": "30006.0174055528",
                        "GeoLocation": null
                    },
                    "PhotoURL": "http://www.meridians2.com/jacksgogo/Content/Images/Profile/4rzg3o0u.jpg",
                    "Title": null,
                    "Email": "Kong@gmail.com",
                    "StripeToken": null,
                    "EmailConfirmed": false,
                    "PasswordHash": "AAdyLMlLBkYZThjCULVQunsM0GivyK8snkQe2iqZ5EqWfbwWNoRQa/5cSCFfea0dRA==",
                    "SecurityStamp": "484f4843-339d-49ad-a1fa-c8160fbb22c7",
                    "PhoneNumber": null,
                    "PhoneNumberConfirmed": false,
                    "TwoFactorEnabled": false,
                    "LockoutEndDateUtc": null,
                    "LockoutEnabled": false,
                    "AccessFailedCount": 0,
                    "Overview": null,
                    "Rate": 0,
                    "Score": null,
                    "Points": null,
                    "DiscountID": null,
                    "Discount": null,
                    "CreatedOn": "2018-12-30T15:23:36.753",
                    "LastLoggedOn": null,
                    "UserName": "Kong",
                    "Tags": []
                }
            },
            {
                "User": {
                    "Id": "d48533ee-94cf-48bc-b84e-ce441dc5fc61",
                    "Surname": null,
                    "GivenName": null,
                    "Gender": true,
                    "Birthday": null,
                    "Address": {
                        "ADDRESS": "18 HAVELOCK ROAD KINDERLAND PRESCHOOL SINGAPORE 059764",
                        "BLK_NO": "18",
                        "BUILDING": "KINDERLAND PRESCHOOL",
                        "LATITUDE": "1.28763824964793",
                        "LONGITUDE": "103.843976681457",
                        "LONGTITUDE": "103.843976681457",
                        "POSTAL": "059764",
                        "ROAD_NAME": "HAVELOCK ROAD",
                        "SEARCHVAL": "KINDERLAND PRESCHOOL",
                        "X": "29186.156914833",
                        "Y": "30006.0174055528",
                        "GeoLocation": null
                    },
                    "PhotoURL": "http://www.meridians2.com/jacksgogo/Content/Images/Profile/4rzg3o0u.jpg",
                    "Title": null,
                    "Email": "Kong@gmail.com",
                    "StripeToken": null,
                    "EmailConfirmed": false,
                    "PasswordHash": "AAdyLMlLBkYZThjCULVQunsM0GivyK8snkQe2iqZ5EqWfbwWNoRQa/5cSCFfea0dRA==",
                    "SecurityStamp": "484f4843-339d-49ad-a1fa-c8160fbb22c7",
                    "PhoneNumber": null,
                    "PhoneNumberConfirmed": false,
                    "TwoFactorEnabled": false,
                    "LockoutEndDateUtc": null,
                    "LockoutEnabled": false,
                    "AccessFailedCount": 0,
                    "Overview": null,
                    "Rate": 0,
                    "Score": null,
                    "Points": null,
                    "DiscountID": null,
                    "Discount": null,
                    "CreatedOn": "2018-12-30T15:23:36.753",
                    "LastLoggedOn": null,
                    "UserName": "Kong",
                    "Tags": []
                }
            },
            {
                "User": {
                    "Id": "d48533ee-94cf-48bc-b84e-ce441dc5fc61",
                    "Surname": null,
                    "GivenName": null,
                    "Gender": true,
                    "Birthday": null,
                    "Address": {
                        "ADDRESS": "18 HAVELOCK ROAD KINDERLAND PRESCHOOL SINGAPORE 059764",
                        "BLK_NO": "18",
                        "BUILDING": "KINDERLAND PRESCHOOL",
                        "LATITUDE": "1.28763824964793",
                        "LONGITUDE": "103.843976681457",
                        "LONGTITUDE": "103.843976681457",
                        "POSTAL": "059764",
                        "ROAD_NAME": "HAVELOCK ROAD",
                        "SEARCHVAL": "KINDERLAND PRESCHOOL",
                        "X": "29186.156914833",
                        "Y": "30006.0174055528",
                        "GeoLocation": null
                    },
                    "PhotoURL": "http://www.meridians2.com/jacksgogo/Content/Images/Profile/4rzg3o0u.jpg",
                    "Title": null,
                    "Email": "Kong@gmail.com",
                    "StripeToken": null,
                    "EmailConfirmed": false,
                    "PasswordHash": "AAdyLMlLBkYZThjCULVQunsM0GivyK8snkQe2iqZ5EqWfbwWNoRQa/5cSCFfea0dRA==",
                    "SecurityStamp": "484f4843-339d-49ad-a1fa-c8160fbb22c7",
                    "PhoneNumber": null,
                    "PhoneNumberConfirmed": false,
                    "TwoFactorEnabled": false,
                    "LockoutEndDateUtc": null,
                    "LockoutEnabled": false,
                    "AccessFailedCount": 0,
                    "Overview": null,
                    "Rate": 0,
                    "Score": null,
                    "Points": null,
                    "DiscountID": null,
                    "Discount": null,
                    "CreatedOn": "2018-12-30T15:23:36.753",
                    "LastLoggedOn": null,
                    "UserName": "Kong",
                    "Tags": []
                }
            },
            {
                "User": {
                    "Id": "d48533ee-94cf-48bc-b84e-ce441dc5fc61",
                    "Surname": null,
                    "GivenName": null,
                    "Gender": true,
                    "Birthday": null,
                    "Address": {
                        "ADDRESS": "18 HAVELOCK ROAD KINDERLAND PRESCHOOL SINGAPORE 059764",
                        "BLK_NO": "18",
                        "BUILDING": "KINDERLAND PRESCHOOL",
                        "LATITUDE": "1.28763824964793",
                        "LONGITUDE": "103.843976681457",
                        "LONGTITUDE": "103.843976681457",
                        "POSTAL": "059764",
                        "ROAD_NAME": "HAVELOCK ROAD",
                        "SEARCHVAL": "KINDERLAND PRESCHOOL",
                        "X": "29186.156914833",
                        "Y": "30006.0174055528",
                        "GeoLocation": null
                    },
                    "PhotoURL": "http://www.meridians2.com/jacksgogo/Content/Images/Profile/4rzg3o0u.jpg",
                    "Title": null,
                    "Email": "Kong@gmail.com",
                    "StripeToken": null,
                    "EmailConfirmed": false,
                    "PasswordHash": "AAdyLMlLBkYZThjCULVQunsM0GivyK8snkQe2iqZ5EqWfbwWNoRQa/5cSCFfea0dRA==",
                    "SecurityStamp": "484f4843-339d-49ad-a1fa-c8160fbb22c7",
                    "PhoneNumber": null,
                    "PhoneNumberConfirmed": false,
                    "TwoFactorEnabled": false,
                    "LockoutEndDateUtc": null,
                    "LockoutEnabled": false,
                    "AccessFailedCount": 0,
                    "Overview": null,
                    "Rate": 0,
                    "Score": null,
                    "Points": null,
                    "DiscountID": null,
                    "Discount": null,
                    "CreatedOn": "2018-12-30T15:23:36.753",
                    "LastLoggedOn": null,
                    "UserName": "Kong",
                    "Tags": []
                }
            }
        ],
        "Report": []
    },
    "Success": true,
    "Message": null,
    "TotalNumber": 0,
    "StripeToken": null
}
